from typing import TypedDict, List, Annotated, Optional
from pydantic import BaseModel

class GraphState(BaseModel):
    first_prompt: str = "" # prompt to be used in the first run of the graph
    first_run: bool = True # is this the initial run of the grap? Yes - a prompt is passed to the first agent, No - a note is passed to the next agent
    notes : List[str] # list of notes generated by the agentic swarm 
    research_quetsions : List[str]