-- Drop table if it exists
DROP TABLE IF EXISTS exoplanet_keys;

-- Create the exoplanet_keys table
CREATE TABLE exoplanet_keys (
    id SERIAL PRIMARY KEY, -- Unique identifier for each key
    key_name TEXT NOT NULL UNIQUE, -- The name of the key (column name from exoplanets table)
    description TEXT NOT NULL -- Description of what the key represents
);

-- Insert key descriptions
INSERT INTO exoplanet_keys (key_name, description) VALUES
    ('pl_name', 'Planet Name'),
    ('hostname', 'Host Star Name'),
    ('default_flag', 'Indicates if this is the default parameter set for the planet'),
    ('sy_snum', 'Number of Stars in the System'),
    ('sy_pnum', 'Number of Planets in the System'),
    ('discoverymethod', 'Discovery Method used to detect the planet'),
    ('disc_year', 'Year the planet was discovered'),
    ('disc_facility', 'Facility or telescope used for discovery'),
    ('soltype', 'Solution Type (e.g., Confirmed, Candidate)'),
    ('pl_controv_flag', 'Flag indicating if the planet is controversial'),
    ('pl_refname', 'Reference for planetary parameters'),
    ('pl_orbper', 'Orbital Period [days]'),
    ('pl_orbpererr1', 'Orbital Period Upper Uncertainty [days]'),
    ('pl_orbpererr2', 'Orbital Period Lower Uncertainty [days]'),
    ('pl_orbperlim', 'Orbital Period Limit Flag'),
    ('pl_orbsmax', 'Orbit Semi-Major Axis [AU]'),
    ('pl_orbsmaxerr1', 'Orbit Semi-Major Axis Upper Uncertainty [AU]'),
    ('pl_orbsmaxerr2', 'Orbit Semi-Major Axis Lower Uncertainty [AU]'),
    ('pl_orbsmaxlim', 'Orbit Semi-Major Axis Limit Flag'),
    ('pl_rade', 'Planet Radius [Earth Radius]'),
    ('pl_radeerr1', 'Planet Radius Upper Uncertainty [Earth Radius]'),
    ('pl_radeerr2', 'Planet Radius Lower Uncertainty [Earth Radius]'),
    ('pl_radelim', 'Planet Radius Limit Flag'),
    ('pl_radj', 'Planet Radius [Jupiter Radius]'),
    ('pl_radjerr1', 'Planet Radius Upper Uncertainty [Jupiter Radius]'),
    ('pl_radjerr2', 'Planet Radius Lower Uncertainty [Jupiter Radius]'),
    ('pl_radjlim', 'Planet Radius Limit Flag'),
    ('pl_bmasse', 'Planet Mass or Mass*sin(i) [Earth Mass]'),
    ('pl_bmasseerr1', 'Planet Mass Upper Uncertainty [Earth Mass]'),
    ('pl_bmasseerr2', 'Planet Mass Lower Uncertainty [Earth Mass]'),
    ('pl_bmasselim', 'Planet Mass Limit Flag'),
    ('pl_bmassj', 'Planet Mass or Mass*sin(i) [Jupiter Mass]'),
    ('pl_bmassjerr1', 'Planet Mass Upper Uncertainty [Jupiter Mass]'),
    ('pl_bmassjerr2', 'Planet Mass Lower Uncertainty [Jupiter Mass]'),
    ('pl_bmassjlim', 'Planet Mass Limit Flag'),
    ('pl_bmassprov', 'Provenance of Mass Measurement'),
    ('pl_orbeccen', 'Orbital Eccentricity'),
    ('pl_orbeccenerr1', 'Orbital Eccentricity Upper Uncertainty'),
    ('pl_orbeccenerr2', 'Orbital Eccentricity Lower Uncertainty'),
    ('pl_orbeccenlim', 'Orbital Eccentricity Limit Flag'),
    ('pl_insol', 'Insolation Flux [Earth Flux]'),
    ('pl_insolerr1', 'Insolation Flux Upper Uncertainty [Earth Flux]'),
    ('pl_insolerr2', 'Insolation Flux Lower Uncertainty [Earth Flux]'),
    ('pl_insollim', 'Insolation Flux Limit Flag'),
    ('pl_eqt', 'Equilibrium Temperature [K]'),
    ('pl_eqterr1', 'Equilibrium Temperature Upper Uncertainty [K]'),
    ('pl_eqterr2', 'Equilibrium Temperature Lower Uncertainty [K]'),
    ('pl_eqtlim', 'Equilibrium Temperature Limit Flag'),
    ('ttv_flag', 'Flag for Transit Timing Variations'),
    ('st_refname', 'Stellar Parameter Reference'),
    ('st_spectype', 'Spectral Type of Host Star'),
    ('st_teff', 'Stellar Effective Temperature [K]'),
    ('st_tefferr1', 'Stellar Effective Temperature Upper Uncertainty [K]'),
    ('st_tefferr2', 'Stellar Effective Temperature Lower Uncertainty [K]'),
    ('st_tefflim', 'Stellar Effective Temperature Limit Flag'),
    ('st_rad', 'Stellar Radius [Solar Radius]'),
    ('st_raderr1', 'Stellar Radius Upper Uncertainty [Solar Radius]'),
    ('st_raderr2', 'Stellar Radius Lower Uncertainty [Solar Radius]'),
    ('st_radlim', 'Stellar Radius Limit Flag'),
    ('st_mass', 'Stellar Mass [Solar Mass]'),
    ('st_masserr1', 'Stellar Mass Upper Uncertainty [Solar Mass]'),
    ('st_masserr2', 'Stellar Mass Lower Uncertainty [Solar Mass]'),
    ('st_masslim', 'Stellar Mass Limit Flag'),
    ('st_met', 'Stellar Metallicity [dex]'),
    ('st_meterr1', 'Stellar Metallicity Upper Uncertainty [dex]'),
    ('st_meterr2', 'Stellar Metallicity Lower Uncertainty [dex]'),
    ('st_metlim', 'Stellar Metallicity Limit Flag'),
    ('st_metratio', 'Stellar Metallicity Ratio'),
    ('st_logg', 'Stellar Surface Gravity [log10(cm/s**2)]'),
    ('st_loggerr1', 'Stellar Surface Gravity Upper Uncertainty [log10(cm/s**2)]'),
    ('st_loggerr2', 'Stellar Surface Gravity Lower Uncertainty [log10(cm/s**2)]'),
    ('st_logglim', 'Stellar Surface Gravity Limit Flag'),
    ('sy_refname', 'System Parameter Reference'),
    ('rastr', 'Right Ascension [Sexagesimal]'),
    ('ra', 'Right Ascension [Degrees]'),
    ('decstr', 'Declination [Sexagesimal]'),
    ('dec', 'Declination [Degrees]'),
    ('sy_dist', 'Distance to System [Parsecs]'),
    ('sy_disterr1', 'Distance Upper Uncertainty [Parsecs]'),
    ('sy_disterr2', 'Distance Lower Uncertainty [Parsecs]'),
    ('sy_vmag', 'V (Johnson) Magnitude'),
    ('sy_vmagerr1', 'V Magnitude Upper Uncertainty'),
    ('sy_vmagerr2', 'V Magnitude Lower Uncertainty'),
    ('sy_kmag', 'Ks (2MASS) Magnitude'),
    ('sy_kmagerr1', 'Ks Magnitude Upper Uncertainty'),
    ('sy_kmagerr2', 'Ks Magnitude Lower Uncertainty'),
    ('sy_gaiamag', 'Gaia Magnitude'),
    ('sy_gaiamagerr1', 'Gaia Magnitude Upper Uncertainty'),
    ('sy_gaiamagerr2', 'Gaia Magnitude Lower Uncertainty'),
    ('rowupdate', 'Date of Last Update'),
    ('pl_pubdate', 'Planetary Parameter Reference Publication Date'),
    ('releasedate', 'Release Date');

SELECT * FROM exoplanet_keys;